//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace Engine.Player.Animations {

	public interface IAnimations {

		void Idle ();
		void Stay ();
		void Walk ();
		void Run ();
		void Attack ();
		void Death ();
		void Damage ();
		void Jump ();
		void Aiming ();
		void Sitdown ();
		void Standup ();

	}

}

