//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace Engine.Player.Animations {

	public interface IAnimations {

		void setIdle ();
		void setStay ();
		void setWalk ();
		void setRun ();
		void setAttack ();
		void setDie ();
		void getDamage ();
		void setJump ();
		void setAiming ();
		void setSitdown ();
		void setStandup ();

	}

}

