//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using Engine.AI.Behavior;

namespace Engine.Player.Animations {

	[RequireComponent (typeof (Animator))]
	public class Actions : MonoBehaviour, IAnimations, IAnimationBehavior {

		private static int maxAttackTreeCount = 2; // число анимационных деревьев для атаки
		private Animator animator;

		public void Start(){
			
			animator = GetComponent<Animator>(); // получаем наш аниматор
			
		}

			void OnGUI(){

			
		
			}

		public void setIdle () {

			animator.SetInteger("Attack",0); // сбрасываем статус атаки

		}

		public void setStay () {
			setIdle();
		}
		
		public void setWalk () {

		}
		
		public void setRun () {

		}
		
		public void setAttack () {
			int newRandomTree = UnityEngine.Random.Range(1,maxAttackTreeCount+1); // выбираем случайный индекс дерева анимации для атаки
			animator.SetInteger("AttackTreeIndex",newRandomTree); // устанавливаем индекс
			animator.SetInteger("Attack",1); // ставим статус атаки
		}
		
		public void setDie () {
			
		}
		
		public void getDamage () {
			
		}
		
		public void setJump () {
			
		}		
		
		public void setAiming () {

		}
		
		public void setSneak () {
			
		}

		public void setSitdown () {
			
		}
		
		public void setStandup () {
			
		}

	}

}

