//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using Random = UnityEngine.Random;

namespace Engine.Player.Animations {

	[RequireComponent (typeof (Animator))]
	public class Actions : MonoBehaviour, IAnimations {

		private static int maxAttackTreeCount = 2; // число анимационных деревьев для атаки
		private Animator animator;

		public void Start(){
			
			animator = GetComponent<Animator>(); // получаем наш аниматор
			
		}

		void OnGUI(){

			
		
		}

		public void Idle () {

			animator.SetInteger("Attack",0); // сбрасываем статус атаки

		}

		public void Stay () {
			Idle();
		}
		
		public void Walk () {
		}
		
		public void Run () {
		}
		
		public void Attack () {
			int newRandomTree = Random.Range(1,maxAttackTreeCount+1); // выбираем случайный индекс дерева анимации для атаки
			animator.SetInteger("AttackTreeIndex",newRandomTree); // устанавливаем индекс
			animator.SetInteger("Attack",1); // ставим статус атаки
		}
		
		public void Death () {
			
		}
		
		public void Damage () {
			
		}
		
		public void Jump () {
			
		}		
		
		public void Aiming () {

		}
		
		public void Sitdown () {
			
		}
		
		public void Standup () {
			
		}

	}

}

