//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Engine.Objects {

	public static class DObjectList {

		public const int S_Health_Potion  = 0xf001;
		public const int S_Mana_Potion    = 0xf002;
		
		public const int S_Raw_Bread     = 0x0003;
		public const int S_Cooked_Bread  = 0x0004;
		public const int S_Raw_Ham       = 0x0005;
		public const int S_Cooked_Ham    = 0x0006;
		public const int S_Raw_Fish      = 0x0007;
		public const int S_Cooked_Fish   = 0x0008;
		
		public const int S_Raw_Green_Apple     = 0x0009;
		public const int S_Cooked_Green_Apple  = 0x000a;
		public const int S_Raw_Red_Apple       = 0x000b;
		public const int S_Cooked_Red_Apple    = 0x000c;

	}

}
